import React from 'react';
import { connect } from 'react-redux';
import { cdn } from 'Root/config';
import Box from 'Root/shared/Box';
import addSign from './add.png';
import styles from './index.less';

const UserDetails = (props) => {
  if (props.user.logged) {
    return (
      <div className={styles.container}>
        <Box className="left">
          <div
            className="avatar"
          >
            <img
              src={props.user.avatar}
              alt="avatar"
            />
            <span>
              <img
                src={addSign}
                alt="add"
              />
            </span>
          </div>
          <p className="name">
            {props.user.firstname} {props.user.lastname}
          </p>
          <p className="username">
            {props.user.username}
          </p>
          <div className="provide">
            <p className="value">
              {props.user.trees.length}
            </p>
            <p className="desc">
              TREES
            </p>
            <div className="divider" />
            <p className="value">
              45,644
            </p>
            <p className="desc">
              <b>
                Oxygens
              </b>
            </p>
          </div>
        </Box>
        <Box className="right">
          <p className="title">
            My Forest on the Planet
          </p>
          <div className="earth">
            <img
              src={`${cdn}/earth.png`}
              alt="earth"
            />
            <div className="circle iran" />
            <div className="circle india" />
            <div className="circle africa" />
          </div>
        </Box>
      </div>
    );
  }

  return (
    <div className={styles.unlogged}>
      <div>
        <p className="title">
          1500 Trees
        </p>
        <p className="desc">
          adopted by Treejer users
        </p>
      </div>
      <div>
        <p className="title">
          327 O<span>2</span> Tokens
        </p>
        <p className="desc">
          generated by adopted Trees
        </p>
      </div>
    </div>
  );
};

export default connect(
  state => ({
    user: state.user,
  }),
)(UserDetails);
